//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabmasterAdminapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PZEntities : DbContext
    {
        public PZEntities()
            : base("name=PZEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grupy> Grupy { get; set; }
        public virtual DbSet<Obecnosci> Obecnosci { get; set; }
        public virtual DbSet<Prowadzacy> Prowadzacy { get; set; }
        public virtual DbSet<Przedmioty> Przedmioty { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<Studenci> Studenci { get; set; }
        public virtual DbSet<StudenciGrupy> StudenciGrupy { get; set; }
        public virtual DbSet<Zajecia> Zajecia { get; set; }
    }
}
