//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabmasterAdminapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obecnosci
    {
        public int id { get; set; }
        public Nullable<int> id_studenta { get; set; }
        public Nullable<int> id_zajec { get; set; }
        public Nullable<bool> obecnosc { get; set; }
        public Nullable<bool> usprawiedliwienie { get; set; }
    
        public virtual Studenci Studenci { get; set; }
        public virtual Zajecia Zajecia { get; set; }
    }
}
