//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabmasterAdminapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zajecia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Zajecia()
        {
            this.Obecnosci = new HashSet<Obecnosci>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_grupy { get; set; }
        public System.DateTime rozpoczecie { get; set; }
        public System.DateTime zakonczenie { get; set; }
        public Nullable<int> id_przedmiotu { get; set; }
        public Nullable<int> id_sali { get; set; }
    
        public virtual Grupy Grupy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obecnosci> Obecnosci { get; set; }
        public virtual Przedmioty Przedmioty { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
